# Generated by Django 4.1.7 on 2023-04-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, unique=True)),
                ('session_start_date', models.DateTimeField(auto_now_add=True)),
                ('organization_info', models.CharField(blank=True, max_length=100)),
                ('country_info', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'ip_data',
            },
        ),
    ]
